apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-deployment
  labels:
    app:  app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app:  app-deployment
    spec:
      containers:
      - name: app-container
        image: ar989827/lanchonete:v1
        ports:
          - containerPort: 8080
        #Liveness Probe
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 110
          periodSeconds: 20
          failureThreshold: 3
        resources:
          limits:
            cpu: 750m 
            memory: 750Mi 
          requests:
            cpu: 250m 
            memory: 250Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgresql-srv:5432/lanchonetedb
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: admin
          - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
            value: org.postgresql.Driver
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            value: none
          - name: SPRING_JPA_DATABASE-PLATFORM
            value: org.hibernate.dialect.PostgreSQLDialect