apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: postgresql-pod
spec:
  containers:
    - name: postgresql
      image: postgres:15
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      env:
        - name: POSTGRES_DB
          value: "lanchonetedb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "admin"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data # Caminho onde o PostgreSQL armazena seus dados
  volumes:
    - name: postgresql-persistent-storage
      persistentVolumeClaim:
        claimName: lanchonete-pvc
