apiVersion: v1
kind: Service
metadata:
  name: postgresql-srv
spec:
  type: NodePort
  ports:
    - port: 5432 # Porta do PostgreSQL
      targetPort: 5432 # Porta interna do contêiner
  selector:
    app: postgresql-pod # Atualize o seletor para o novo nome do Pod
