apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanchonete-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/frbastos/Documents/FIAP/Arquitetura de Software/Projeto/fiap-software-architecture-lanchonete/infra"