spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
      show-sql: true
      database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    properties:
      hibernate:
        format_sql: false
  flyway:
    locations: classpath:db/migration/postgres
