# Server
server:
  port: 8080

# Spring
spring:
  main:
    allow-circular-references: true
  application:
    name: lanchonete

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
swagger-ui:
  path: /swagger-ui.html
