server:
    port: 8080

spring:

  main:
    allow-circular-references: true

  application:
    name: lanchonete

    # H2 configuration
    # datasource:
    #   url: jdbc:h2:mem:lanchonetedb
    #   driverClassName: org.h2.Driver
    # h2:
    #   console:
    #     enabled: true
    #     path: /h2-console

   # MYSQL configuration
    datasource:
      #url: jdbc:mysql://db:3306/lanchonetedb
      #username: sa
      #password: password
      driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate:
          format_sql: true

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
  swagger-ui:
    path: /swagger-ui.html

# RabbitMQ
  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: /




