INSERT INTO product (id, description, price, category) VALUES (1,'X-Salada', 25.00, 'SNACK');
INSERT INTO product (id, description, price, category) VALUES (2, 'X-Bacon', 30.00, 'SNACK');
INSERT INTO product (id, description, price, category) VALUES (3, 'X-Egg', 27.00, 'SNACK');
INSERT INTO product (id, description, price, category) VALUES (4, 'Bata Frita', 12.00, 'SIDE_DISH');
INSERT INTO product (id, description, price, category) VALUES (5, 'Polenta Frita', 12.00, 'SIDE_DISH');
INSERT INTO product (id, description, price, category) VALUES (6, 'Bata Frota com Cheeder e Bacon', 20.00, 'SIDE_DISH');
INSERT INTO product (id, description, price, category) VALUES (7, 'Coca-Cola', 7.00, 'DRINK');
INSERT INTO product (id, description, price, category) VALUES (8, 'Guaraná', 7.00, 'DRINK');
INSERT INTO product (id, description, price, category) VALUES (9, 'Pepsi', 7.00, 'DRINK');
INSERT INTO product (id, description, price, category) VALUES (10, 'Pudim', 7.00, 'DESSERT');
INSERT INTO product (id, description, price, category) VALUES (11, 'Sorvete', 5.00, 'DESSERT');