name: Deploy to Docker

on:
  push:
    # branches:
    #   - main 
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      #Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      #Configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construir o JAR com Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Configurar o DOCKER
      - name: Login to DockerHub
        run: docker login -u ar989827 -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir e enviar a imagem para o Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ar989827/lanchonete:${{ github.sha }} .
          docker push ar989827/lanchonete:${{ github.sha }}

      # Configurar kubectl para acessar o cluster EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name dev-fiap-eks-cluster --region us-east-1

      # Atualizar deployment no EKS
      - name: Update Deployment
        run: |
          kubectl set image deployment/app-deployment app-container=ar989827/lanchonete:${{ github.sha }}
          kubectl rollout status deployment/app-deployment