name: Deploy to Docker
on:
  push:
    branches:
      - feat/infra
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      #Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      #Configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construir o JAR com Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Configurar o DOCKER
      - name: Login to DockerHub
        run: docker login -u ar989827 -p ${{ secrets.DOCKERHUB_TOKEN }}

      #  Construir e enviar a imagem para o Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ar989827/lanchonete .
          docker push ar989827/lanchonete

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f node-deployment.yaml 
      #     kubectl apply -f node-service.yaml 
